feat(posts): implement posts API endpoints
Tonyrj3268/Processes pull request #36
Opened 2024-11-03 14:27 UTC by Arui1122

2024-11-03 15:22 UTC, Tonyrj3268 commented
我還沒有細看，不過你可以先處理
- gitignore添加DS_Store，把你交上來的那格移除掉
- 解釋一下為什麼要額外做一個那個type，我已經有寫index.t.s了，理論上要獲得user直接使用request.user就好，沒必要多引入一個IUserRequest
- 你的roter不需要這行吧，(req: IUserRequest, res: Response) => void，可以參考我的寫法
- 你好像提交了空的package.json和lock.json，理論不應該存在？

2024-11-03 17:01 UTC, Tonyrj3268 requested changes

2024-11-03 17:01 UTC, Tonyrj3268 commented on backend/tests/services/postService.test.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
避免檢查的理由是？

2024-11-03 17:01 UTC, Tonyrj3268 commented on backend/tests/services/postService.test.ts
> +            ];
跟另一個測試的問題差不多

2024-11-03 17:09 UTC, Tonyrj3268 commented
我同意你在service做檢查是否存在的作法，而不是在controller層，我之後會把user也改掉
例如這個
```
async followUser(req: Request, res: Response): Promise<void> {
    const user = req.user as IUserDocument;
    const { userId } = req.body;
    try {
      const followedUser = await this.userService.findUserById(userId);
      if (!followedUser) {
        res.status(404).json({ msg: "使用者不存在" });
        return;
      }
      const result = await this.userService.followUser(user, followedUser);
      if (!result) {
        res.status(409).json({ msg: "已經追蹤該使用者" });
        return;
      }
      res.status(200).json({ msg: "成功追蹤使用者" });
    } catch (err) {
      console.error(err);
      res.status(500).json({ msg: "伺服器發生錯誤" });
    }
  }
```

我應該會改成類似這樣
```
async followUser(req: Request, res: Response): Promise<void> {
    const user = req.user as IUserDocument;
    const { userId } = req.body;
    try {
      const result = await this.userService.followUser(user, followedUser);
      if (!result) {
        res.status(409).json({ msg: "已經追蹤該使用者" });
        return;
      }
      res.status(200).json({ msg: "成功追蹤使用者" });
    } catch (err) {
        if(err === notFoundError){
        res.status(404).json({ msg: "使用者不存在" });
        return;
      }
      console.error(err);
      res.status(500).json({ msg: "伺服器發生錯誤" });
    }
  }
```

2024-11-04 04:54 UTC, Arui1122 commented on backend/src/services/postService.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
因為有些變數我宣告後沒用，或是引入套件沒用，他會有紅色波浪符很醜。

2024-11-04 05:47 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
沒用到的話，要嘛是先保留然後mark起來，要嘛是寫個TODO，要嘛是變數前面加一個 "_"，最後才是選擇使用
`// eslint-disable-next-line @typescript-eslint/no-unused-vars`，不過怎樣都不會使用全局的這個

2024-11-04 05:57 UTC, Arui1122 commented on backend/src/types/express.ts
> +}
整合到原本你的type了

2024-11-04 06:12 UTC, Tonyrj3268 commented on backend/src/types/express.ts
> +}
你這個也沒有錯，你這個相對職權明確，我用的那個是因為我判斷幾乎所有的api都需要有user這個屬性且都一定會經過jwt驗證，各有各得好

2024-11-04 08:12 UTC, Arui1122 commented on backend/src/controllers/postController.ts
> +                }
make sense

2024-11-04 08:34 UTC, Arui1122 commented on backend/src/controllers/postController.ts
> +            }
JWT middleware 會確保 req.user 存在

2024-11-04 09:10 UTC, Tonyrj3268 commented
你的DS_store還是存在，查一下有辦法把它去掉

2024-11-04 09:21 UTC, Tonyrj3268 commented
btw 我目前是打算把check build這個CI移動到最後一步，檢查完測試和eslint後才進行，因為有機會編譯的文件被eslint檔下來，但理論上我們不該對編譯後的檔案做額外操作

2024-11-04 09:28 UTC, Tonyrj3268 requested changes

2024-11-04 09:28 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +                    content: post.content.substring(0, 50)
你這個應該要放在detail裡面
可以參考這個做法
```
type DetailValue = Types.ObjectId | string | number | boolean;

const details = new Map<string, DetailValue>();

```

2024-11-04 09:28 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +                    content: content.substring(0, 50)
和上面一樣

2024-11-04 12:33 UTC, Arui1122 commented on backend/tests/controllers/postController.test.ts
> +    });
根據 src/middlewares/authenticateJWT.ts 的設定，未認證的請求會被 passport JWT middleware 攔截，根本不會到達 controller。make sense!

2024-11-04 14:42 UTC, Arui1122 commented on backend/tests/services/postService.test.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
backend git:(feature/posts-api) ✗ npm run lint

> backend@1.0.0 lint
> eslint .


/Users/arui/project/Processes/backend/tests/controllers/postController.test.ts
   22:19  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  342:26  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/arui/project/Processes/backend/tests/services/postService.test.ts
  14:17  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 3 problems (3 errors, 0 warnings)

2024-11-04 14:43 UTC, Arui1122 commented on backend/tests/services/postService.test.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
找不到什麼寫法可以不用any，所以暫時保留/* eslint-disable @typescript-eslint/no-explicit-any */

2024-11-04 15:02 UTC, Arui1122 commented on backend/eslint.config.mjs
> +      "@typescript-eslint/no-explicit-any": "off",
明天再改不用any的test

2024-11-04 15:30 UTC, Tonyrj3268 commented on backend/tests/setup.ts
> +  const uri = await mongoReplSet.getUri();
改這裡的理由是什麼？

2024-11-04 15:45 UTC, Tonyrj3268 commented on backend/eslint.config.mjs
> +      "@typescript-eslint/no-explicit-any": "off",
我看了一下你的any的問題都來自mock的對象，你只要從model層import 有繼承過document的interface就可以把any取代了

2024-11-05 05:29 UTC, Tonyrj3268 commented on backend/tests/setup.ts
> +  const uri = await mongoReplSet.getUri();
https://typegoose.github.io/mongodb-memory-server/docs/guides/migration/migrate7/#no-function-other-than-start-create-ensureinstance-will-be-starting-anything

你把這個改回去test解決一半

2024-11-05 05:34 UTC, Tonyrj3268 commented on backend/tests/setup.ts
> +  const uri = await mongoReplSet.getUri();
另一半等你把model改成我們群組說的那樣就解決了

2024-11-05 16:00 UTC, Tonyrj3268 requested changes

2024-11-05 16:00 UTC, Tonyrj3268 commented on .DS_Store
把這個移除掉

2024-11-05 16:23 UTC, Tonyrj3268 commented
我不小心直接push到main，所以很多檔案不在這了，我直接打給你要多加什麼
controller/postController.ts
1. getAllPosts要支持分頁，你不能一次把資料庫所有的post回傳回去
service/postService.ts
1. getAllPosts要支持分頁，你不能一次把資料庫所有的post回傳回去
2. deletePost Post.findOne和findByIdAndDelete可以合在一起
3. 有很多都和上面一樣的狀況是可以和再一起的，這樣可以減少操作資料庫的次數，你找找然後修改一下
4. 調整 Promise.all 的使用，只對獨立操作使用 Promise.all，保證操作順序在有依賴關係時是正確的，像是按讚的話，應該是建立玩like後才調整數量，而不是並行處理，可能會導致出問題

基本上把service改一改，測試簡單調整一下就差不多了

2024-11-08 10:10 UTC, Arui1122 commented
@Tonyrj3268 comment model當時候我們為什麼留{ discriminatorKey: "kind", timestamps: true }啊？還是他其實不需要。

2024-11-08 10:12 UTC, Tonyrj3268 commented
> @Tonyrj3268 comment model當時候我們為什麼留{ discriminatorKey: "kind", timestamps: true }啊？還是他其實不需要。

不需要，不用kind了

2024-11-08 10:17 UTC, Tonyrj3268 commented
啊我看你傳了一堆意義不明的檔案，處理一下ㄅ

2024-11-08 10:34 UTC, Arui1122 commented
為什麼force push完PR就被close＝＝

2024-11-08 12:45 UTC, Arui1122 commented
@Tonyrj3268 我在想我把 add comment拉到 commentContoller/Service，這樣分離好像比較好。另外 like/unlike post 這些跟 like 有關的操作放到 likeController/service。

2024-11-08 13:01 UTC, Tonyrj3268 commented
> @Tonyrj3268 我在想我把 add comment拉到 commentContoller/Service，這樣分離好像比較好。另外 like/unlike post 這些跟 like 有關的操作放到 likeController/service。

也許可以吧，雖然我覺得再分like就多了

2024-11-08 13:20 UTC, Arui1122 commented
@Tonyrj3268 算了我覺得維持post, commemt自己下面都有createComment這個method好了，剛看到你openAPI spec都寫好了，也不是不行。

2024-11-28 07:45 UTC, merged