Feature/comment api
Tonyrj3268/Processes pull request #40
Opened 2024-11-08 17:06 UTC by Arui1122

2024-11-09 06:58 UTC, Tonyrj3268 requested changes

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/controllers/postController.ts
> +                    postsPerPage: limit
因為thread是很難有上限的，每次都要去查全部有幾筆很花費時間，我們只要獲得每次要幾個貼文（limit)和上一次最後一篇貼文的ID(cursor)，從那一筆根據時間推算新的limit數量貼文就好

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/controllers/postController.ts
> +            res.status(201).json({ msg: "Post created successfully" });
真的不需要主動返回新的或是更新後的貼文嗎？

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +    async getAllPosts(page: number = 1, limit: number = 10): Promise<{ posts: IPost[]; total: number }> {
cursor and limit

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +                Post.countDocuments(),
貼文是否公開？

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +                    })
不會在首頁看到評論內容

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +                likesCount: 0  // 初始化按讚計數
有默認

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
> +            return !!result;  // 轉換為布林值
確認一下findOneAndUpdate會不會造成有貼文沒更新卻返回true的情況

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
>                  ]);
Like.findOneAndUpdate // 嘗試插入 Like 記錄，若已存在則不插入
Post有使用findById，不需要先確認有沒有存在

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
>                      ),
和上一個一樣

2024-11-09 06:58 UTC, Tonyrj3268 commented on backend/src/services/postService.ts
>                  );
可以使用post.update就好，你前面已經find了

2024-11-09 09:03 UTC, Arui1122 commented on backend/src/services/commentService.ts
> +                comments: []
ok，但comments沒有default empty array

2024-11-09 10:15 UTC, Arui1122 commented on backend/src/services/commentService.ts
> +                comments: []
@Tonyrj3268 我們comment, post model的comments欄位是要 ?: undefined，到service自己處理判斷。還是說直接給他default 空陣列啊？

2024-11-09 10:42 UTC, Arui1122 commented on backend/src/services/commentService.ts
> +                comments: []
算了我都幫他們default設為空陣列好了，我servive再修改一下。

2024-11-09 15:25 UTC, Arui1122 commented on backend/src/services/postService.ts
> +            return !!result;  // 轉換為布林值
findOneAndUpdate在找不到文檔時會返回null，所以轉換為boolean後會是false

2024-11-09 16:01 UTC, Arui1122 commented
等等，那個like如果要加到comment跟post後，邏輯會變得超難雞掰＝＝

2024-11-09 16:16 UTC, Tonyrj3268 commented
難點在哪？我看邏輯很正確啊？

2024-11-09 16:21 UTC, Tonyrj3268 commented
之前有說過其實可以不用處理重複按讚吧？

2024-11-09 17:38 UTC, Arui1122 commented
抱歉我忘記了。所以是 case1: 還沒按讚（愛心是空心的），會call likeComment這個api。case2: 假如已經按過讚（愛心是實心紅色的），這樣我再按一次就直接call unlikeComment的 api，我就不用再likeComment api判斷是不是重複按讚了。不過這樣就是前端需要維護愛心的狀態對吧？

2024-11-09 18:39 UTC, Tonyrj3268 commented
> 抱歉我忘記了。所以是 case1: 還沒按讚（愛心是空心的），會call likeComment這個api。case2: 假如已經按過讚（愛心是實心紅色的），這樣我再按一次就直接call unlikeComment的 api，我就不用再likeComment api判斷是不是重複按讚了。不過這樣就是前端需要維護愛心的狀態對吧？

對，因為正常來說不會有人一直對同一篇貼文call like，就算有可能也是來亂的，那我們對來亂的就直接跟他說２００而不是花時間去做後面操作，之後也能對同user對某api做速率限制。
所以比較有可能的是前端按愛心後，api會切換成unlike，要擔心的是like/unlike一直被切換call，這可能等有queue後會比較不用擔心。

2024-11-22 06:12 UTC, Tonyrj3268 requested changes

2024-11-28 07:45 UTC, Tonyrj3268 approved these changes

2024-11-28 07:45 UTC, merged