feat: add register and login page
Tonyrj3268/Processes pull request #43
Opened 2024-11-13 13:37 UTC by MiaaaChen

2024-11-14 01:24 UTC, Tonyrj3268 requested changes
一些好奇的問題而已

2024-11-14 01:24 UTC, Tonyrj3268 commented on frontend/src/pages/Login.tsx
> +  };
這裏不會導致setShowError執行兩次嗎？還是沒差？

2024-11-14 01:24 UTC, Tonyrj3268 commented on frontend/src/pages/Login.tsx
> +            color: "333",
這個要#字號嗎？我看上面有

2024-11-14 06:16 UTC, MiaaaChen commented on frontend/src/pages/Login.tsx
> +  };
你是指 L23 嗎？這裡是如果 email 或密碼沒填就跳 error message，如果都填了就 set false 不顯示 error message，所以應該不會執行兩次

2024-11-14 06:28 UTC, MiaaaChen commented
authRoutes.ts 這段的 error message 要再寫清楚一點嗎？目前不管是 email 還是密碼錯，都是顯示 Invalid email or password.

<img width="687" alt="截圖 2024-11-14 14 24 19" src="https://github.com/user-attachments/assets/36267aa4-0fdf-49a3-9bc2-418bbcb07ae2">

2024-11-22 09:06 UTC, gahwa17 approved these changes

2024-11-22 09:18 UTC, Tonyrj3268 approved these changes

2024-11-22 09:18 UTC, merged